[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bengara-rs/bengara"
authors = ["bengara contributors"]

[workspace.dependencies]
bengara-build = { path = "crates/bengara-build", version = "=0.1.0" }
bengara-macros = { path = "crates/bengara-macros", version = "=0.1.0" }

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
